# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B899DF1F8-2F43-4394-8315-37F6744E6319%7D:1.0.9.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "76.2.1");
user_pref("extensions.lastPlatformVersion", "76.2.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{899DF1F8-2F43-4394-8315-37F6744E6319}\":{\"d\":\"D:\\\\!!!!!!!@@@@@@!!!!!!!\\\\xxxxx\\\\@@@@\\\\!@@@@@@@@@@@!\\\\New folder\\\\@@@\\\\K-Melon Light PWA Able WebBrowser\\\\browser\\\\extensions\\\\{899DF1F8-2F43-4394-8315-37F6744E6319}.xpi\",\"e\":true,\"v\":\"1.0.9.1\",\"st\":1451929464968}}}");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("image.http.accept", "image/webp,image/jxr,image/png,image/*;q=0.8,*/*;q=0.5");
user_pref("kmeleon.MRU.URL0", "www.google.ca");
user_pref("kmeleon.display.XPos", 80);
user_pref("kmeleon.display.YPos", 43);
user_pref("kmeleon.display.height", 774);
user_pref("kmeleon.display.width", 1200);
user_pref("kmeleon.plugins.adblock.load", true);
user_pref("kmeleon.plugins.macros.accel.mouse.configs", "Firefox;SeaMonkey;Opera;");
user_pref("kmeleon.plugins.macros.encoding.cache.size", 5);
user_pref("kmeleon.plugins.macros.reload.interval", 120);
user_pref("kmeleon.plugins.macros.translate.menu.regions", "1111111");
user_pref("kmeleon.plugins.macros.translate.service.langpairs", "");
user_pref("kmeleon.plugins.macros.translate.service.name", "&Google Translate");
user_pref("kmeleon.plugins.macros.translate.service.regions", "1111111");
user_pref("kmeleon.plugins.macros.translate.service.url.page", "https://translate.google.com/translate?u=<url>&hl=<to>&ie=UTF8&sl=<from>&tl=<to>");
user_pref("kmeleon.plugins.macros.translate.service.url.text", "https://translate.google.com/translate_t?langpair=<from>|<to>&text=<txt>");
user_pref("kmeleon.plugins.macros.translate.to", "en");
user_pref("kmeleon.plugins.macros.zoom", "text");
user_pref("kmeleon.plugins.sessions.cleanShutdown", true);
user_pref("kmeleon.plugins.update.lastcheck", 1608955059);
user_pref("kmeleon.prefs_inited", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("toolkit.telemetry.previousBuildID", "7621");
